language: ruby
cache: bundler

bundler_args: --without local_development
before_install:
  - gem install bundler

script: bundle exec rake

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2
  - rbx-3

env:
  global:
    - JRUBY_OPTS="--server -J-Xms1500m -J-Xmx1500m -J-XX:+UseConcMarkSweepGC -J-XX:-UseGCOverheadLimit -J-XX:+CMSClassUnloadingEnabled"
    - RUBYOPT="-w"
  matrix:
    - MBCHARS=activesupport
    - MBCHARS=builtin

matrix:
  include:
    - rvm: 1.8.7
      dist: precise
      env: MBCHARS=builtin
    - rvm: 1.8.7
      dist: precise
      env: MBCHARS=activesupport
    - rvm: 1.9.2
      dist: trusty
      env: MBCHARS=builtin
    - rvm: 1.9.2
      dist: trusty
      env: MBCHARS=activesupport
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-3
  fast_finish: true
