language: ruby
bundler_args: --path vendor/bundle
script: bundle exec rake
env:
  - RUBYOPT=-w
before_install:
  - gem install bundler
  - bundle config --local without local_development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head    # green, but unstable
    - rvm: jruby-head   # green, but unstable
    - rvm: rbx-2        # see https://github.com/rubinius/rubinius/issues/3050
  fast_finish: true
